const GET_USER = "user:GET_USER";
const UPDATE_PROFILE = "user:UPDATE_PROFILE";
const SOFT_DELETE_USER = "user:SOFT_DELETE_USER";
const DELETE_USER = "user:DELETE_USER";
const GET_ALL_USERS = "user:GET_ALL_USERS";
const GET_ALL_USERS_DELETED = "user:GET_ALL_USERS_DELETED";
const RESERT_PASSWORD = "user:RESET_PASSWORD";
const ADD_NEW_ADMIN = "admin:ADD_NEW_ADMIN"
const REMOVE_ADMIN = "admin:REMOVE_ADMIN"
const GET_ALL_ADMINS = "admin:GET_ALL_ADMINS"


module.exports = {
    GET_ALL_USERS,
    GET_USER, UPDATE_PROFILE,
    SOFT_DELETE_USER,
    DELETE_USER,
    RESERT_PASSWORD,
    GET_ALL_USERS_DELETED,
    ADD_NEW_ADMIN,
    REMOVE_ADMIN,
    GET_ALL_ADMINS
}