const {RESERT_PASSWORD, GET_USER, GET_ALL_USERS_DELETED,GET_ALL_USERS, DELETE_USER, SOFT_DELETE_USER, UPDATE_PROFILE } = require("../../modules/users/endPoint");

module.exports = [GET_USER, GET_ALL_USERS, DELETE_USER, GET_ALL_USERS_DELETED,SOFT_DELETE_USER, UPDATE_PROFILE,RESERT_PASSWORD]