const {
    ADD_NEW_ADMIN,
    REMOVE_ADMIN,
    GET_ALL_ADMINS,
    GET_USER,
    GET_ALL_USERS,
    DELETE_USER,
    SOFT_DELETE_USER,
    GET_ALL_USERS_DELETED,
    UPDATE_PROFILE,
    RESERT_PASSWORD
} = require("../../modules/users/endPoint");

module.exports = [
    ADD_NEW_ADMIN,
    REMOVE_ADMIN,
    GET_ALL_ADMINS,
    GET_USER,
    GET_ALL_USERS,
    GET_ALL_USERS_DELETED,
    DELETE_USER,
    SOFT_DELETE_USER,
    UPDATE_PROFILE,
    RESERT_PASSWORD
]